spring:
  datasource:
    url: jdbc:postgresql://qa-server:5432/minimarket_qa
    username: qa_user
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  rabbitmq:
    host: qa-rabbit
    port: 5672
    username: qa_user
    password: ${RABBIT_PASSWORD}

logging:
  level:
    root: INFO